
version: '3.8'
services:
  app:
    image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION_1.amazonaws.com/thrive:latest
    ports:
      - 3000:3000
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=$AWS_ACCOUNT_ID.$AWS_REGION_2.compute.amazonaws.com
      - PGUSER=postgres
      - PGPASSWORD=postgres
    restart: always
