version: "3.8"
services:
  api:
    build:
        dockerfile: Dockerfile
        context: .
    depends_on: 
        - postgres
    environment: 
        DATABASE_URL: postgres://alicehuang:postgres@postgres:5432/db
        NODE_ENV: development
        PORT: 3000
    ports:
        - "8080:3000"

  postgres:
    image: postgres:latest
    ports:
        - "35000:5432"
    environment: 
        POSTGRES_USER: alicehuang
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: db