version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: alicehccn/thrive:latest
    ports:
      - 3000:3000
    environment:
      - POSTGRES_PORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres
    depends_on:
      - db
