version: 2.1
jobs:
  build-deploy:
    docker:
      - image: circleci/python:3.6.1
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/repo
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - install-aws-venv
      - setup-env-variables
      - build-docker-image
      - push-docker-image

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - build-deploy:
          filters:
            branches:
              only:
                - main
          context:
            - docker-hub-creds
            - alicehccn

commands:
  install-aws-venv:
    description: "Install AWS in venv"
    steps:
      - run:
          name: Install awscli
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install awscli>=1.16.116

  setup-env-variables:
    description: "Setup common environment variables"
    steps:
      - run:
          name: Setup ENV Variables
          command: |
            echo 'export FULL_IMAGE_NAME="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/alicehccn/thrive:${CIRCLE_BRANCH}-${CIRCLE_SHA1}"' >> $BASH_ENV

  build-docker-image:
    description: "Build Docker Image"
    steps:
      - run:
          name: Build Docker Image
          command: |
            docker build -f .deployment/Dockerfile -t $FULL_IMAGE_NAME .

  push-docker-image:
      description: "Push Docker Image"
      steps:
        - run:
            name: Push image
            command: |
              . venv/bin/activate
              docker login
              