version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/repo
    steps:
      - checkout
      - install-aws-venv
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Setup common environment variables
          command: |
            echo 'export FULL_IMAGE_NAME="686971707721.dkr.ecr.us-west-2.amazonaws.com/alicehccn/thrive:${CIRCLE_BRANCH}-${CIRCLE_SHA1}"' >> $BASH_ENV
      - run:
          name: Build image
          command: |
            echo $FULL_IMAGE_NAME
            docker build -f .deployment/Dockerfile -t $FULL_IMAGE_NAME .

      - push-docker-image

commands:
  install-aws-venv:
    description: "Install AWS in venv"
    steps:
      - run:
          name: Install awscli
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install awscli>=1.16.116
      - run:
          name: Login AWS ECR
          command: |
            aws ecr get-login-password | docker login --username AWS --password-stdin 686971707721.dkr.ecr.us-west-2.amazonaws.com

  push-docker-image:
      description: "Push Docker Image"
      steps:
        - run:
            name: Push image
            command: |
              . venv/bin/activate
              eval $(aws ecr get-login --region us-west-2 --no-include-email)
              docker push 686971707721.dkr.ecr.us-west-2.amazonaws.com/alicehccn/thrive:$CIRCLE_BRANCH-$CIRCLE_SHA1


workflows:
  version: 2.1
  unit-build:
    jobs:
      - build
