version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.7
  aws-cli: circleci/aws-cli@3.1.1

  # aws-ecr: circleci/aws-ecr@8.1.2

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-and-test:
    # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # A list of available CircleCI Docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/node
    docker:
      - image: cimg/node:16.10
    # Then run your tests!
    # CircleCI will report the results back to your VCS provider.
    steps:
      # Checkout the code as the first step.
      - checkout
      # Next, the node orb's install-packages step will install the dependencies from a package.json.
      # The orb install-packages step will also automatically cache them for faster future runs.
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run format
          command: npm run format
      - run:
          name: Run eslint
          command: npm run lint

      # - run:
      #     name: Run tests
          # command: npm test

  deploy:
      executor: aws-cli/default
      steps:
        - checkout
        - aws-cli/setup:
            profile-name: example
        - run:
            name: Login AWS ECR
            command: docker login -u AWS -p $(aws configure)


workflows:
  version: 2.1
  party-time:
    jobs:
      - build-and-test
      - deploy
